#!/bin/bash
#
# apply_patchs.sh - apply AML patches with git am (one commit per patch).
#
# Patches under aml_patch/ are generated by git format-patch, so each
# file carries its original commit header (author, date, subject,
# Signed-off-by).  git am re-creates one commit per patch with exactly
# that information, like kernel common_drivers auto_patch.sh.
#
# Behaviour per patch (sorted by filename):
#   1. already applied (reverse-check passes) -> skipped
#   2. not applied yet  -> git am creates the commit
#   3. git am fails     -> abort, nothing is left half-applied
#
# NOTE: patches must be in git format-patch format (mail header with
# a Subject line).  Run on a tree where the files the patches touch
# are clean; other local edits to those files would make git am fail.
#
# Usage: aml_patch/apply_patchs.sh   (called by mk.sh before building)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "${ROOT_DIR}"

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
	echo "[ERROR] not inside a git repository"
	exit 1
}

if [ -f .git/MERGE_HEAD ] || [ -d .git/rebase-merge ] || [ -d .git/rebase-apply ]; then
	echo "[ERROR] a merge/rebase is in progress, resolve it first"
	exit 1
fi

echo "========================================"
echo "Apply AML patches (git am)"
echo "Patch dir: ${SCRIPT_DIR}"
echo "========================================"

APPLIED=0
SKIPPED=0

for patch in $(find "${SCRIPT_DIR}" -maxdepth 1 -type f -name '*.patch' | sort -V); do
	patch_name="$(basename "${patch}")"

	echo
	echo ">>> ${patch_name}"

	# Already applied?  The patch applies in reverse, so its content
	# is already in the tree.  git am commits the patch content
	# atomically, so this also means it is already committed.
	if git apply --reverse --check "${patch}" >/dev/null 2>&1; then
		echo "[SKIP ] already applied"
		SKIPPED=$((SKIPPED + 1))
		continue
	fi

	# git am: one commit per patch, info from the patch header.
	# --keep-cr keeps CRLF patch context intact (e.g. kernel.c).
	if git am --keep-cr -q "${patch}"; then
		echo "[ OK  ] $(git log --oneline -1)"
		APPLIED=$((APPLIED + 1))
	else
		git am --abort 2>/dev/null || true
		echo "[ERROR] ${patch_name} cannot be applied"
		echo
		echo "Possible reasons:"
		echo "  - patch conflicts with current source"
		echo "  - previous patch was not applied correctly"
		echo "  - patch is partially applied"
		echo
		echo "Stop applying following patches."
		exit 1
	fi
done

echo
echo "========================================"
echo "All AML patches processed: ${APPLIED} committed, ${SKIPPED} skipped."
echo "========================================"
